name: x_flutter
description: Matrix Restful Api Flutter Package. You can build user, forum, social, chat, any other apps with Matrix.
version: 0.0.7
homepage: https://github.com/withcenter/x_flutter
repository: https://github.com/withcenter/x_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
